### ISSUE TITLE
Balance on Imp Extract seems off

### ISSUE THREAD

**Issue by GalacticRuler** [KevinfromHP/KevinsAdditionalItems#1]
What I mean is, the player feels very fragile despite getting the HP scaling on the Imp Overlord; and doesn't appear to do much damage. In addition, losing all of your items while transformed makes it very difficult to survive past stage 5 or 6 in monsoon with this item.

**Comment by KevinfromHP** [comment]
I completely missed this and am very sorry about that lol

As for the item, it has had a pretty big rework today. If you end up trying it out, I wouldn't mind feedback on the changes.
