### ISSUE TITLE
Seeking Stone Issues

### ISSUE THREAD

**Issue by LittleXT** [KevinfromHP/KevinsAdditionalItems#2]
So I was trying the mod with Captain and picked up Seeking Stone and didn't think too much about it until I used my orbital strike and then it infinitely kept using the strike. So I decided to recreate the situation and sure enough Seeking Stone was causing the problem so I tried it on a few other survivors and it seems that Artificer has the same issue with her ice wall and the item.

**Comment by KevinfromHP** [comment]
Hey, I addressed this issue in a patch I released earlier today. Thanks for the report though!
