### ISSUE TITLE
Seeking Stone breaks engineers Thermal Harpoons skill

### ISSUE THREAD

**Issue by Alumx** [KevinfromHP/KevinsAdditionalItems#3]
If picked up, the thermal harpoons stay frozen in the same place where they've been shot

**Comment by KevinfromHP** [comment]
Hey, somehow these issues slipped past me during initial testing of the item, I think I rolled over a change afterward that broke these. However, I fixed this in the release earlier today. Reply to me here if you still have any issues with it. Also, I'm realizing that Engie's bouncy grenades get the same projectile buff that the others do lol, they go really far now. I'll probably fix that.
