### ISSUE TITLE
Imp Extract + Equipment Drone

### ISSUE THREAD

**Issue by ryocryte** [KevinfromHP/KevinsAdditionalItems#5]
Tried out the Imp Extract on the equipment drone during a run today, and to my surprise the drone actually used it and transformed into an Imp Overlord. However, the drone didn't really know how to attack, so he sorta just wandered around until the effect wore off. Is there anyway to fix this?

**Comment by KevinfromHP** [comment]
Hey, I've been aware of this issue. Unfortunately in this case, there is genuinely no way to fix it because the fix would permanently turn the drone into an Imp. Sorry about that.
